Classification logistic regression
Tara-Sophia/NLP_Masterthesis pull request #14
Opened 2022-10-13 11:49 UTC by HannahPetry

# PR Description

## Please check if the PR fulfills these requirements

- [ ] Tests for the changes have been added (for bug fixes/features) (Or not needed)
- [ ] Labels, reviewers and assignees have been added to the pull request
- [ ] Docs have been added / updated (for bug fixes / features) (Or not needed)

## Motivation and Context

## Does this PR introduce a breaking change?

## Other information

2022-10-18 09:32 UTC, florentinvonhaugwitz commented on .gitignore
> +data/en_ner_bionlp13cg_md-0.5.1/
Können wir diesen Ordner in einen subfolder von data verschieben? Am besten data/external/en_ner_biolon13cg_md-0.5.1/

2022-10-18 10:32 UTC, florentinvonhaugwitz reviewed
Das ist richtiger guter Hannah!! Sehr organisiert und strukturiert. Ich habe ein paar Anmerkungen bei kleineren Sachen aber die Logik erscheint mir richtig und umfänglich! Falls du ein paar meiner Kommentare anders siehst, dann schreib es einfach dazu - letzlich sind es ja nur Anregungen

2022-10-18 10:32 UTC, florentinvonhaugwitz commented on .gitignore
> +data/en_ner_bionlp13cg_md-0.5.1/
Ich sehe außerdem die ganzen files aus diesem Ordner auch im PR. Kannst du die wieder rausnehmen damit wir die nicht hochladen am Ende?

2022-10-18 10:32 UTC, florentinvonhaugwitz commented on src/models/predict_lr_model.py
> +    model_name = "./models/sklearn_logistic_regression_model.pkl"
Hier würde ich mit os.path.join() arbeiten, damit wir sicherstellen können, dass es auf allen Computern funktioniert

2022-10-18 10:32 UTC, florentinvonhaugwitz commented on src/models/predict_lr_model.py
> +    model = joblib.load(filename=model_name)
Ist joblib besser als `pickle.dump(model, open('model.pkl', 'wb'))`?

2022-10-18 10:32 UTC, florentinvonhaugwitz commented on src/models/predict_lr_model.py
> +    model_name = "./models/sklearn_logistic_regression_model.pkl"
Vielleicht können wir auch model_name als Paramter für die Funktion nutzen und dann können wir diese Funktion generisch für andere Modell auch benutzen

2022-10-18 10:32 UTC, florentinvonhaugwitz commented on src/models/predict_lr_model.py
> +        model
Hier am besten noch beschreiben was das genau für ein Parameter sit

2022-10-18 10:32 UTC, florentinvonhaugwitz commented on src/models/predict_lr_model.py
> +def load_model() -> object:
In dem Fall wird nicht ein object sondern ein imblearn.pipeline.Pipeline Wert zurückgegeben

2022-10-18 10:32 UTC, florentinvonhaugwitz commented on src/models/predict_lr_model.py
> +def predict_probability(model: object, value: str, category_list: list) -> pd.DataFrame:
Hier muss auch object auch wieder zu imblearn.pipeline.Pipeline
Und am besten auch angeben was für werte in list übergeben werden, also List[str] (https://stackoverflow.com/questions/24853923/type-hinting-a-collection-of-a-specified-type)

2022-10-18 10:32 UTC, florentinvonhaugwitz commented on src/models/predict_lr_model.py
> +    model : object
Hier wieder imblearn.pipeline.Pipeline

2022-10-18 10:32 UTC, florentinvonhaugwitz commented on src/models/predict_lr_model.py
> +    print(model)
Das können wir rausnehmen

2022-10-18 10:32 UTC, florentinvonhaugwitz commented on src/models/predict_lr_model.py
> +    print(prob_df)
Ist das einfach ein Beispielwert zur Veranschaulichung?

2022-10-18 10:32 UTC, florentinvonhaugwitz commented on src/models/train_lr_model.py
> +def get_labels(df: pd.DataFrame) -> list:
Hier auch angeben was für einen art von Liste es ist

2022-10-18 10:32 UTC, florentinvonhaugwitz commented on src/models/train_lr_model.py
> +def split_data(df: pd.DataFrame) -> array:
Der Rückgabewert ist glaube ich ein Tupel von np.arrays

2022-10-18 10:32 UTC, florentinvonhaugwitz commented on src/models/train_lr_model.py
> +def build_pipeline() -> imbPipeline:
Hier ist der Rückgabewert glaube ich auch imblearn.pipeline.Pipeline

2022-10-18 10:32 UTC, florentinvonhaugwitz commented on src/models/train_lr_model.py
> +) -> GridSearchCV:
Müsste der Rückgabewert nicht auch ein Model sein, da wir ja den besten estimator zurückgeben?
Am besten einmal `print(type(search.best_estimator_))` ausführen vor dem return wert um zu sehen was er da ausgibt

2022-10-20 06:41 UTC, HannahPetry commented on src/models/train_lr_model.py
> +def get_labels(df: pd.DataFrame) -> list:
Mein type(get_labels(df_test)) ist einfach list. Kann man das noch spezifizieren oder meinst du im #Titel der Funktion?

2022-10-20 11:06 UTC, HannahPetry commented on src/models/predict_lr_model.py
> +    print(prob_df)
Ja, genau. Das funktioniert momentan nur leider noch nicht mit einem value.

2022-11-07 21:39 UTC, florentinvonhaugwitz reviewed
Am besten alle "test" models im Ordner models/clf löschen

2022-11-07 21:54 UTC, florentinvonhaugwitz requested changes
Weiterhin sehr guter code! 
Meiner Meinung nach fehlen nur noch die paar Kleinigkeiten, die ich angemerkt habe, dann
am besten die main branch in deine branch ziehen (können wir gerne auch morgen zusammen machen) und `pre-commit run --all-files` einmal laufen lassen und gucken ob es durch geht. 
Die docs können wir gerne auch morgen zusammen machen

2022-11-07 21:54 UTC, florentinvonhaugwitz commented on src/clf/create_data.py
> +    )
Am besten ist es wenn du für alle Files oder sonstigen Konstanten einen "constants.py" anlegst der die alle beinhaltet

2022-11-07 21:54 UTC, florentinvonhaugwitz commented on src/clf/create_data.py
> +    print(test_df.head())
Ist das zur Überprüfung?

2022-11-07 21:54 UTC, florentinvonhaugwitz commented on src/clf/evaluation.py
> +def _reciprocal_rank(true_labels: list, machine_preds: list) -> float:
Wieso hat die Funktion einen Unterstrich?

2022-11-07 21:54 UTC, florentinvonhaugwitz commented on src/clf/evaluation.py
> +def compute_mrr_at_k(items: list) -> float:
Wenn der type list ist, dann am besten angeben was dort entalten ist. Also in diesem Fall list[tuples[str, str]]

2022-11-07 21:54 UTC, florentinvonhaugwitz commented on src/clf/evaluation.py
> +def _reciprocal_rank(true_labels: list, machine_preds: list) -> float:
Die werte von list auch noch angeben

2022-11-07 21:54 UTC, florentinvonhaugwitz commented on src/clf/evaluation.py
> +) -> list:
Wert für list angeben

2022-11-07 21:54 UTC, florentinvonhaugwitz commented on src/clf/evaluation.py
> +        print("MRR @3: ", mrr)
Nice! Sehr gut!

2022-11-07 21:54 UTC, florentinvonhaugwitz commented on src/clf/lr_training.py
> +from traitlets import List
Bist du sicher dass wir diesen import brauchen?

2022-11-07 21:54 UTC, florentinvonhaugwitz commented on src/clf/lr_training.py
> +def build_pipeline(pipeline) -> imblearn.pipeline.Pipeline:
type von pipeline angeben

2022-11-07 21:54 UTC, florentinvonhaugwitz commented on src/clf/lr_training.py
> +        pipeline with preprocessing steps
Absatz

2022-11-07 21:54 UTC, florentinvonhaugwitz commented on src/clf/lr_training.py
> +    train_file_path = os.path.join("data", "processed", "clf", "train.csv")
Den file path auch in den constants file schieben

2022-11-07 21:54 UTC, florentinvonhaugwitz commented on src/clf/lr_training.py
> +    test_file_path = os.path.join("data", "processed", "clf", "test.csv")
Den file path auch in den constants file schieben

2022-11-07 21:54 UTC, florentinvonhaugwitz commented on src/clf/lr_training.py
> +    return model
Im Zweifel kannst du diese Methode auch rausnehmen da sie nur eine Zeile lang ist. Da ist es schneller sie direkt in der main methode auszuführen

2022-11-07 21:54 UTC, florentinvonhaugwitz commented on src/clf/predict.py
> +    coef_df = coef_df.abs()
Wieso machen wir nochmal .abs()?

2022-11-07 21:54 UTC, florentinvonhaugwitz commented on src/streamlit/predict_lr_new.py
> +    *
Kann weg

2022-11-07 21:54 UTC, florentinvonhaugwitz commented on src/streamlit/predict_lr_new.py
> +    return model
Kannst du direkt implementieren ohne Funktion, da es nur eine Zeile ist

2022-11-08 10:10 UTC, HannahPetry commented on src/clf/predict.py
> +    coef_df = coef_df.abs()
Das muss ich abändern, das war noch mit allen coefficients, auch negativen. Gut, dass du das gesehen hast. Man muss sich ja nur die größten positiven coefficients angeben lassen, richtig?

2022-11-08 10:13 UTC, HannahPetry commented on src/clf/create_data.py
> +    print(test_df.head())
Ja, nehm ich raus.

2022-11-08 16:28 UTC, florentinvonhaugwitz submitted a review, later dismissed

2022-11-08 16:51 UTC, florentinvonhaugwitz approved these changes

2022-11-08 16:51 UTC, merged