Data preprocessing
Tara-Sophia/NLP_Masterthesis pull request #16
Opened 2022-11-03 15:49 UTC by Tara-Sophia

# PR Description

## Please check if the PR fulfills these requirements

- [ ] Tests for the changes have been added (for bug fixes/features) (Or not needed)
- [ ] Labels, reviewers and assignees have been added to the pull request
- [ ] Docs have been added / updated (for bug fixes / features) (Or not needed)

## Motivation and Context

## Does this PR introduce a breaking change?

## Other information

2022-11-08 18:08 UTC, florentinvonhaugwitz reviewed
Alle files im Ordner "Data" aufräumen und in den richtigen Ordner schieben

2022-11-08 18:54 UTC, florentinvonhaugwitz reviewed
Sehr guter Code! Gute und klare Funktionen obwohl es oft sehr komple Aufgaben sind. Für mich ergibt der Code sinn. Ansonsten überall noch docstrings und type hinting hinzufügen und die Stukture bei allen files sollte die gleiche sein. Ebenfalls die files in data noch aufräumen
@HannahPetry bitte auch nochmal drübergehen

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/streamlit_02/helper_02.py
> +import string
Unused import of string

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/streamlit_02/helper_02.py
> +def KeywordExtraction(text):
Docstrings und type hinting fehlt

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/apply_KB_semisupervised.py
> +def KeywordExtraction(df):
type hinting und docstring hinzufügen

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/apply_KB_semisupervised.py
> +        "models/nlp/semi_supervised/model", model_max_lenght=512
Den file path in einen file "constants.py" hinzufügen und mit os.path.join() erstellen damit er auch auf anderen Computern funktioniert

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/apply_KB_semisupervised.py
> +        model="models/nlp/semi_supervised/model",
Die gleich constant wie oben benutzen

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/apply_KB_semisupervised.py
> +    df = small_column_df(df_1)
Das sollten wir nochmal versuchen zu schaffen, dass wir das nicht mehr brauchen

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/apply_KB_semisupervised.py
> +    df_1 = pd.read_csv("data/processed/nlp/mtsamples/mtsamples_cleaned.csv")
Die Namen sollten am besten selbsterklärend sein. Also nicht df1 oder so benutzen

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/apply_KB_semisupervised.py
> +import string
Das kann weg

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/apply_KB_unsupervised.py
> +        "models/nlp/unsupervised/model", model_max_lenght=512
Auch in constants.py hinzufügen

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/apply_KB_unsupervised.py
> +    )
Wenn diese Funktion die gleich Funktion wie im KB unsupervised file ist, dann sollte sie in den utils file kommen und nur noch einmal existieren

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/apply_KB_unsupervised.py
> +    )
Sollte auch nur noch einmal existieren

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/cleaning.py
> +def cleaning_input(sentence):
type hinting und docstrings noch hinzufügen

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/cleaning.py
> +    ]
Sehr gut!

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/cleaning.py
> +    return df[df["medical_specialty"].isin(top_11)].copy()
Nochmal Hannah fragen was die Kriterien genau sind um die top 11 Classes zu bekommen

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/cleaning.py
> +    print(df.shape)
Am besten rausnehmen

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/cleaning.py
> +    print(df.shape)
Auch rausnehmen

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/predicting.py
> +# nltk.download("omw-1.4")
Kann man das nicht alles löschen?

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/predicting.py
> +    print(keywords)
Nice! Sehr gut verständlich!

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/semi_supervised_training.py
> +wandb.init(project="nlp", entity="nlp_masterthesis")
Hier noch "tags" hinzufügen mit der Art des models. Also `tags=["unsupervised"]`

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/training.py
> +tokenizer = AutoTokenizer.from_pretrained(checkpoint)
Auch in main methode

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/training.py
> +from transformers import Trainer, TrainingArguments, AutoModelForSequenceClassification
Nach oben

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/training.py
> +    trainer.save_model("./results_modelBert")
Wieso bleibst du bei diesem File nicht bei der gleichen Struktur wie bei dem unsupervised_training file?

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/unsupervised_training.py
> +from transformers import DataCollatorForLanguageModeling
Zusammenfassen in einen import

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/unsupervised_training.py
> +)
Das auch noch hinzuüfgen

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/unsupervised_training.py
> +from constants import *
Einzeln importieren

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/unsupervised_training.py
> +    import math
Nach oben

2022-11-08 18:54 UTC, florentinvonhaugwitz commented on src/nlp/unsupervised_training.py
> +    print(f"Perplexity: {math.exp(eval_results['eval_loss']):.2f}")
Ich würde ein eigenenen evaluate file erstellen

2022-11-08 18:55 UTC, florentinvonhaugwitz commented
Ich habe den PR jetzt geteilt. Die restlichen Files sind in diesem PR #18

2022-11-09 12:59 UTC, HannahPetry commented on src/nlp/cleaning.py
> +    return df[df["medical_specialty"].isin(top_11)].copy()
Das Kriterium war nur labels, die mehr als 100 mal vorkommen, zu berücksichtigen. Das sind dann 11 labels, könnte man aber auch umschreiben um nicht manuell 11 einzusetzen.

2022-11-17 10:05 UTC, florentinvonhaugwitz commented on src/nlp/KeyBert_on_Mtsamples.py
> +def KeywordExtraction(x: str, model, nr_candidates: int, top_n: int) -> list[tuple]:
Functions should be lowercase

2022-11-17 10:05 UTC, florentinvonhaugwitz commented on src/nlp/KeyBert_on_Mtsamples.py
> +# -*- coding: utf-8 -*-
Filenames should be lowercase

2022-11-17 10:08 UTC, florentinvonhaugwitz commented on src/nlp/KeyBert_on_Mtsamples.py
> +        nr_candidates = 35
Why do we have 35 written here?

2022-11-17 10:18 UTC, florentinvonhaugwitz requested changes
The code is way way better and cleaner than last time! Very nice! Only small things are missing. Also the folder names should stay consistent. The models are still in folders called unsupervised and supervised although the filenames have changed

2022-11-17 10:18 UTC, florentinvonhaugwitz commented on src/nlp/KeyBert_on_Mtsamples.py
> +    df["top_n"] = df["nr_candidates"].apply(lambda x: round(x * 0.5))
Why are we multiplying time 0.5?

2022-11-17 10:18 UTC, florentinvonhaugwitz commented on src/nlp/MaskedLanguageModel_training.py
> +# -*- coding: utf-8 -*-
Lowercase filename

2022-11-17 10:18 UTC, florentinvonhaugwitz commented on src/nlp/MaskedLanguageModel_training.py
> +wandb.init(project="nlp", entity="nlp_masterthesis")
Include tags, so that we are consistent

2022-11-17 10:18 UTC, florentinvonhaugwitz commented on src/nlp/MaskedLanguageModel_training.py
> +    df_mlm = df_mlm.head(20)
Why are we only loading the top 20?

2022-11-17 10:18 UTC, florentinvonhaugwitz commented on src/nlp/MaskedLanguageModel_training.py
> +    # AutoModelForSequenceClassification.from_pretrained(
Couldn't this just be `model = BertForMaskedLM.from_pretrained("bert-case-cased").to(device)`

2022-11-17 10:18 UTC, florentinvonhaugwitz commented on src/nlp/MaskedLanguageModel_training.py
> +    bert_type = "bert-base-cased"
Should this be part of the constants file?

2022-11-17 10:18 UTC, florentinvonhaugwitz commented on src/nlp/TextClassification_training.py
> +wandb.init(project="nlp", entity="nlp_masterthesis")
Use tags

2022-11-17 10:18 UTC, florentinvonhaugwitz commented on src/nlp/TextClassification_training.py
> +        path to the csv file
Docstrings should be consistent. Either they should start lowercase or uppercase everytime

2022-11-17 10:18 UTC, florentinvonhaugwitz commented on src/nlp/TextClassification_training.py
> +    df = df.head(10)
Is this a todo? Why are we using this for training?

2022-11-17 10:18 UTC, florentinvonhaugwitz commented on src/nlp/cleaning.py
> +    most_common_words_filtered,
This should also be in ALL_CAPS

2022-11-17 10:18 UTC, florentinvonhaugwitz commented on src/nlp/constants.py
> +most_common_words_filtered = [
ALL_CAPS as well

2022-11-17 10:18 UTC, florentinvonhaugwitz commented on src/nlp/utils.py
> +# all the functions which are used multiple times
Bruchen wir den auskommentierten Code noch?

2022-11-17 16:53 UTC, florentinvonhaugwitz approved these changes, later dismissed

2022-11-17 19:39 UTC, florentinvonhaugwitz approved these changes

2022-11-17 19:41 UTC, merged